version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db-1
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=contrasenia
    command: sh -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=contrasenia
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=contrasenia
