<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('iso2');
            $table->string('iso3');
            $table->string('phone_code')->nullable();
        });

        $countries = [
            ['name' => 'Afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'phone_code' => '+93'],
            ['name' => 'Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'phone_code' => '+355'],
            ['name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'phone_code' => '+49'],
            ['name' => 'Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'phone_code' => '+376'],
            ['name' => 'Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'phone_code' => '+244'],
            ['name' => 'Anguilla', 'iso2' => 'AI', 'iso3' => 'AIA', 'phone_code' => '+1 264'],
            ['name' => 'Antarctica', 'iso2' => 'AQ', 'iso3' => 'ATA', 'phone_code' => '+672'],
            ['name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'phone_code' => '+1 268'],
            ['name' => 'Saudi Arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'phone_code' => '+966'],
            ['name' => 'Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'phone_code' => '+213'],
            ['name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'phone_code' => '+54'],
            ['name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'phone_code' => '+374'],
            ['name' => 'Aruba', 'iso2' => 'AW', 'iso3' => 'ABW', 'phone_code' => '+297'],
            ['name' => 'Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'phone_code' => '+61'],
            ['name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'phone_code' => '+43'],
            ['name' => 'Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'phone_code' => '+994'],
            ['name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'phone_code' => '+32'],
            ['name' => 'Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'phone_code' => '+1 242'],
            ['name' => 'Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'phone_code' => '+973'],
            ['name' => 'Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'phone_code' => '+880'],
            ['name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'phone_code' => '+1 246'],
            ['name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'phone_code' => '+501'],
            ['name' => 'Benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'phone_code' => '+229'],
            ['name' => 'Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'phone_code' => '+975'],
            ['name' => 'Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'phone_code' => '+375'],
            ['name' => 'Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'phone_code' => '+95'],
            ['name' => 'Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'phone_code' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'phone_code' => '+387'],
            ['name' => 'Botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'phone_code' => '+267'],
            ['name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'phone_code' => '+55'],
            ['name' => 'Brunei', 'iso2' => 'BN', 'iso3' => 'BRN', 'phone_code' => '+673'],
            ['name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'phone_code' => '+359'],
            ['name' => 'Burkina Faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'phone_code' => '+226'],
            ['name' => 'Burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'phone_code' => '+257'],
            ['name' => 'Cape Verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'phone_code' => '+238'],
            ['name' => 'Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'phone_code' => '+855'],
            ['name' => 'Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'phone_code' => '+237'],
            ['name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'phone_code' => '+1'],
            ['name' => 'Chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'phone_code' => '+235'],
            ['name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'phone_code' => '+56'],
            ['name' => 'China', 'iso2' => 'CN', 'iso3' => 'CHN', 'phone_code' => '+86'],
            ['name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'phone_code' => '+357'],
            ['name' => 'Vatican City State', 'iso2' => 'VA', 'iso3' => 'VAT', 'phone_code' => '+39'],
            ['name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'phone_code' => '+57'],
            ['name' => 'Comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'phone_code' => '+269'],
            ['name' => 'Republic of the Congo', 'iso2' => 'CG', 'iso3' => 'COG', 'phone_code' => '+242'],
            ['name' => 'Democratic Republic of the Congo', 'iso2' => 'CD', 'iso3' => 'COD', 'phone_code' => '+243'],
            ['name' => 'North Korea', 'iso2' => 'KP', 'iso3' => 'PRK', 'phone_code' => '+850'],
            ['name' => 'South Korea', 'iso2' => 'KR', 'iso3' => 'KOR', 'phone_code' => '+82'],
            ['name' => 'Ivory Coast', 'iso2' => 'CI', 'iso3' => 'CIV', 'phone_code' => '+225'],
            ['name' => 'Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'phone_code' => '+506'],
            ['name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'phone_code' => '+385'],
            ['name' => 'Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'phone_code' => '+53'],
            ['name' => 'Curazao', 'iso2' => 'CW', 'iso3' => 'CWU', 'phone_code' => '+5999'],
            ['name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'phone_code' => '+45'],
            ['name' => 'Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'phone_code' => '+1 767'],
            ['name' => 'Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'phone_code' => '+593'],
            ['name' => 'Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'phone_code' => '+20'],
            ['name' => 'El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'phone_code' => '+503'],
            ['name' => 'United Arab Emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'phone_code' => '+971'],
            ['name' => 'Eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'phone_code' => '+291'],
            ['name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'phone_code' => '+421'],
            ['name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'phone_code' => '+386'],
            ['name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'phone_code' => '+34'],
            ['name' => 'United States of America', 'iso2' => 'US', 'iso3' => 'USA', 'phone_code' => '+1'],
            ['name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'phone_code' => '+372'],
            ['name' => 'Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'phone_code' => '+251'],
            ['name' => 'Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'phone_code' => '+63'],
            ['name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'phone_code' => '+358'],
            ['name' => 'Fiji', 'iso2' => 'FJ', 'iso3' => 'FJI', 'phone_code' => '+679'],
            ['name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'phone_code' => '+33'],
            ['name' => 'Gabon', 'iso2' => 'GA', 'iso3' => 'GAB', 'phone_code' => '+241'],
            ['name' => 'Gambia', 'iso2' => 'GM', 'iso3' => 'GMB', 'phone_code' => '+220'],
            ['name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'phone_code' => '+995'],
            ['name' => 'Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'phone_code' => '+233'],
            ['name' => 'Gibraltar', 'iso2' => 'GI', 'iso3' => 'GIB', 'phone_code' => '+350'],
            ['name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'phone_code' => '+1 473'],
            ['name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'phone_code' => '+30'],
            ['name' => 'Greenland', 'iso2' => 'GL', 'iso3' => 'GRL', 'phone_code' => '+299'],
            ['name' => 'Guadeloupe', 'iso2' => 'GP', 'iso3' => 'GLP', 'phone_code' => '+590'],
            ['name' => 'Guam', 'iso2' => 'GU', 'iso3' => 'GUM', 'phone_code' => '+1 671'],
            ['name' => 'Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'phone_code' => '+502'],
            ['name' => 'French Guiana', 'iso2' => 'GF', 'iso3' => 'GUF', 'phone_code' => '+594'],
            ['name' => 'Guernsey', 'iso2' => 'GG', 'iso3' => 'GGY', 'phone_code' => '+44'],
            ['name' => 'Guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'phone_code' => '+224'],
            ['name' => 'Equatorial Guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'phone_code' => '+240'],
            ['name' => 'Guinea-Bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'phone_code' => '+245'],
            ['name' => 'Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'phone_code' => '+592'],
            ['name' => 'Haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'phone_code' => '+509'],
            ['name' => 'Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'phone_code' => '+504'],
            ['name' => 'Hong Kong', 'iso2' => 'HK', 'iso3' => 'HKG', 'phone_code' => '+852'],
            ['name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'phone_code' => '+36'],
            ['name' => 'India', 'iso2' => 'IN', 'iso3' => 'IND', 'phone_code' => '+91'],
            ['name' => 'Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'phone_code' => '+62'],
            ['name' => 'Iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'phone_code' => '+98'],
            ['name' => 'Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'phone_code' => '+964'],
            ['name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'phone_code' => '+353'],
            ['name' => 'Bouvet Island', 'iso2' => 'BV', 'iso3' => 'BVT'],
            ['name' => 'Isle of Man', 'iso2' => 'IM', 'iso3' => 'IMN', 'phone_code' => '+44'],
            ['name' => 'Christmas Island', 'iso2' => 'CX', 'iso3' => 'CXR', 'phone_code' => '+61'],
            ['name' => 'Norfolk Island', 'iso2' => 'NF', 'iso3' => 'NFK', 'phone_code' => '+672'],
            ['name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'phone_code' => '+354'],
            ['name' => 'Bermuda Islands', 'iso2' => 'BM', 'iso3' => 'BMU', 'phone_code' => '+1 441'],
            ['name' => 'Cayman Islands', 'iso2' => 'KY', 'iso3' => 'CYM', 'phone_code' => '+1 345'],
            ['name' => 'Cocos (Keeling) Islands', 'iso2' => 'CC', 'iso3' => 'CCK', 'phone_code' => '+61'],
            ['name' => 'Cook Islands', 'iso2' => 'CK', 'iso3' => 'COK', 'phone_code' => '+682'],
            ['name' => 'Aland Islands', 'iso2' => 'AX', 'iso3' => 'ALA', 'phone_code' => '+358'],
            ['name' => 'Faroe Islands', 'iso2' => 'FO', 'iso3' => 'FRO', 'phone_code' => '+298'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'iso2' => 'GS', 'iso3' => 'SGS', 'phone_code' => '+500'],
            ['name' => 'Heard Island and McDonald Islands', 'iso2' => 'HM', 'iso3' => 'HMD'],
            ['name' => 'Maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'phone_code' => '+960'],
            ['name' => 'Falkland Islands (Malvinas)', 'iso2' => 'FK', 'iso3' => 'FLK', 'phone_code' => '+500'],
            ['name' => 'Northern Mariana Islands', 'iso2' => 'MP', 'iso3' => 'MNP', 'phone_code' => '+1 670'],
            ['name' => 'Marshall Islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'phone_code' => '+692'],
            ['name' => 'Pitcairn Islands', 'iso2' => 'PN', 'iso3' => 'PCN', 'phone_code' => '+870'],
            ['name' => 'Solomon Islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'phone_code' => '+677'],
            ['name' => 'Turks and Caicos Islands', 'iso2' => 'TC', 'iso3' => 'TCA', 'phone_code' => '+1 649'],
            ['name' => 'United States Minor Outlying Islands', 'iso2' => 'UM', 'iso3' => 'UMI', 'phone_code' => '+246'],
            ['name' => 'Virgin Islands', 'iso2' => 'VG', 'iso3' => 'VGB', 'phone_code' => '+1 284'],
            ['name' => 'United States Virgin Islands', 'iso2' => 'VI', 'iso3' => 'VIR', 'phone_code' => '+1 340'],
            ['name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'phone_code' => '+972'],
            ['name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'phone_code' => '+39'],
            ['name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'phone_code' => '+1 876'],
            ['name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'phone_code' => '+81'],
            ['name' => 'Jersey', 'iso2' => 'JE', 'iso3' => 'JEY', 'phone_code' => '+44'],
            ['name' => 'Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'phone_code' => '+962'],
            ['name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'phone_code' => '+7'],
            ['name' => 'Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'phone_code' => '+254'],
            ['name' => 'Kyrgyzstan', 'iso2' => 'KG', 'iso3' => 'KGZ', 'phone_code' => '+996'],
            ['name' => 'Kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'phone_code' => '+686'],
            ['name' => 'Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'phone_code' => '+965'],
            ['name' => 'Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'phone_code' => '+961'],
            ['name' => 'Laos', 'iso2' => 'LA', 'iso3' => 'LAO', 'phone_code' => '+856'],
            ['name' => 'Lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'phone_code' => '+266'],
            ['name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'phone_code' => '+371'],
            ['name' => 'Liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'phone_code' => '+231'],
            ['name' => 'Libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'phone_code' => '+218'],
            ['name' => 'Liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'phone_code' => '+423'],
            ['name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'phone_code' => '+370'],
            ['name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'phone_code' => '+352'],
            ['name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'phone_code' => '+52'],
            ['name' => 'Monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'phone_code' => '+377'],
            ['name' => 'Macao', 'iso2' => 'MO', 'iso3' => 'MAC', 'phone_code' => '+853'],
            ['name' => 'Macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'phone_code' => '+389'],
            ['name' => 'Madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'phone_code' => '+261'],
            ['name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'phone_code' => '+60'],
            ['name' => 'Malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'phone_code' => '+265'],
            ['name' => 'Mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'phone_code' => '+223'],
            ['name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'phone_code' => '+356'],
            ['name' => 'Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'phone_code' => '+212'],
            ['name' => 'Martinique', 'iso2' => 'MQ', 'iso3' => 'MTQ', 'phone_code' => '+596'],
            ['name' => 'Mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'phone_code' => '+230'],
            ['name' => 'Mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'phone_code' => '+222'],
            ['name' => 'Mayotte', 'iso2' => 'YT', 'iso3' => 'MYT', 'phone_code' => '+262'],
            ['name' => 'Estados Federados de', 'iso2' => 'FM', 'iso3' => 'FSM', 'phone_code' => '+691'],
            ['name' => 'Moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'phone_code' => '+373'],
            ['name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'phone_code' => '+976'],
            ['name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'phone_code' => '+382'],
            ['name' => 'Montserrat', 'iso2' => 'MS', 'iso3' => 'MSR', 'phone_code' => '+1 664'],
            ['name' => 'Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'phone_code' => '+258'],
            ['name' => 'Namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'phone_code' => '+264'],
            ['name' => 'Nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'phone_code' => '+674'],
            ['name' => 'Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'phone_code' => '+977'],
            ['name' => 'Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'phone_code' => '+505'],
            ['name' => 'Niger', 'iso2' => 'NE', 'iso3' => 'NER', 'phone_code' => '+227'],
            ['name' => 'Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'phone_code' => '+234'],
            ['name' => 'Niue', 'iso2' => 'NU', 'iso3' => 'NIU', 'phone_code' => '+683'],
            ['name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'phone_code' => '+47'],
            ['name' => 'New Caledonia', 'iso2' => 'NC', 'iso3' => 'NCL', 'phone_code' => '+687'],
            ['name' => 'New Zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'phone_code' => '+64'],
            ['name' => 'Oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'phone_code' => '+968'],
            ['name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'phone_code' => '+31'],
            ['name' => 'Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'phone_code' => '+92'],
            ['name' => 'Palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'phone_code' => '+680'],
            ['name' => 'Palestine', 'iso2' => 'PS', 'iso3' => 'PSE', 'phone_code' => '+970'],
            ['name' => 'Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'phone_code' => '+507'],
            ['name' => 'Papua New Guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'phone_code' => '+675'],
            ['name' => 'Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'phone_code' => '+595'],
            ['name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'phone_code' => '+51'],
            ['name' => 'French Polynesia', 'iso2' => 'PF', 'iso3' => 'PYF', 'phone_code' => '+689'],
            ['name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'phone_code' => '+48'],
            ['name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'phone_code' => '+351'],
            ['name' => 'Puerto Rico', 'iso2' => 'PR', 'iso3' => 'PRI', 'phone_code' => '+1'],
            ['name' => 'Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'phone_code' => '+974'],
            ['name' => 'United Kingdom', 'iso2' => 'GB', 'iso3' => 'GBR', 'phone_code' => '+44'],
            ['name' => 'Central African Republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'phone_code' => '+236'],
            ['name' => 'Czech Republic', 'iso2' => 'CZ', 'iso3' => 'CZE', 'phone_code' => '+420'],
            ['name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'phone_code' => '+1 809'],
            ['name' => 'South Sudan', 'iso2' => 'SS', 'iso3' => 'SSD', 'phone_code' => '+211'],
            ['name' => 'Réunion', 'iso2' => 'RE', 'iso3' => 'REU', 'phone_code' => '+262'],
            ['name' => 'Rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'phone_code' => '+250'],
            ['name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'phone_code' => '+40'],
            ['name' => 'Russia', 'iso2' => 'RU', 'iso3' => 'RUS', 'phone_code' => '+7'],
            ['name' => 'Western Sahara', 'iso2' => 'EH', 'iso3' => 'ESH', 'phone_code' => '+212'],
            ['name' => 'Samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'phone_code' => '+685'],
            ['name' => 'American Samoa', 'iso2' => 'AS', 'iso3' => 'ASM', 'phone_code' => '+1 684'],
            ['name' => 'Saint Barthélemy', 'iso2' => 'BL', 'iso3' => 'BLM', 'phone_code' => '+590'],
            ['name' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'phone_code' => '+1 869'],
            ['name' => 'San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'phone_code' => '+378'],
            ['name' => 'Saint Martin (French part)', 'iso2' => 'MF', 'iso3' => 'MAF', 'phone_code' => '+1 599'],
            ['name' => 'Saint Pierre and Miquelon', 'iso2' => 'PM', 'iso3' => 'SPM', 'phone_code' => '+508'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'phone_code' => '+1 784'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso2' => 'SH', 'iso3' => 'SHN', 'phone_code' => '+290'],
            ['name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'phone_code' => '+1 758'],
            ['name' => 'Sao Tome and Principe', 'iso2' => 'ST', 'iso3' => 'STP', 'phone_code' => '+239'],
            ['name' => 'Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'phone_code' => '+221'],
            ['name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'phone_code' => '+381'],
            ['name' => 'Seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'phone_code' => '+248'],
            ['name' => 'Sierra Leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'phone_code' => '+232'],
            ['name' => 'Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'phone_code' => '+65'],
            ['name' => 'Sint Maarten', 'iso2' => 'SX', 'iso3' => 'SMX', 'phone_code' => '+1 721'],
            ['name' => 'Syria', 'iso2' => 'SY', 'iso3' => 'SYR', 'phone_code' => '+963'],
            ['name' => 'Somalia', 'iso2' => 'SO', 'iso3' => 'SOM', 'phone_code' => '+252'],
            ['name' => 'Sri Lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'phone_code' => '+94'],
            ['name' => 'South Africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'phone_code' => '+27'],
            ['name' => 'Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'phone_code' => '+249'],
            ['name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'phone_code' => '+46'],
            ['name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'phone_code' => '+41'],
            ['name' => 'Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'phone_code' => '+597'],
            ['name' => 'Svalbard and Jan Mayen', 'iso2' => 'SJ', 'iso3' => 'SJM', 'phone_code' => '+47'],
            ['name' => 'Swaziland', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'phone_code' => '+268'],
            ['name' => 'Tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'phone_code' => '+992'],
            ['name' => 'Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'phone_code' => '+66'],
            ['name' => 'Taiwan', 'iso2' => 'TW', 'iso3' => 'TWN', 'phone_code' => '+886'],
            ['name' => 'Tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'phone_code' => '+255'],
            ['name' => 'British Indian Ocean Territory', 'iso2' => 'IO', 'iso3' => 'IOT', 'phone_code' => '+246'],
            ['name' => 'French Southern Territories', 'iso2' => 'TF', 'iso3' => 'ATF', 'phone_code' => '+'],
            ['name' => 'East Timor', 'iso2' => 'TL', 'iso3' => 'TLS', 'phone_code' => '+670'],
            ['name' => 'Togo', 'iso2' => 'TG', 'iso3' => 'TGO', 'phone_code' => '+228'],
            ['name' => 'Tokelau', 'iso2' => 'TK', 'iso3' => 'TKL', 'phone_code' => '+690'],
            ['name' => 'Tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'phone_code' => '+676'],
            ['name' => 'Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'phone_code' => '+1 868'],
            ['name' => 'Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'phone_code' => '+216'],
            ['name' => 'Turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'phone_code' => '+993'],
            ['name' => 'Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'phone_code' => '+90'],
            ['name' => 'Tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'phone_code' => '+688'],
            ['name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'phone_code' => '+380'],
            ['name' => 'Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'phone_code' => '+256'],
            ['name' => 'Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'phone_code' => '+598'],
            ['name' => 'Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'phone_code' => '+998'],
            ['name' => 'Vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'phone_code' => '+678'],
            ['name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'phone_code' => '+58'],
            ['name' => 'Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'phone_code' => '+84'],
            ['name' => 'Wallis and Futuna', 'iso2' => 'WF', 'iso3' => 'WLF', 'phone_code' => '+681'],
            ['name' => 'Yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'phone_code' => '+967'],
            ['name' => 'Djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'phone_code' => '+253'],
            ['name' => 'Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'phone_code' => '+260'],
            ['name' => 'Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'phone_code' => '+263'],
    
            // Agrega el resto de los países aquí
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert($country);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
};